### ISSUE TITLE
I registered the account, ready to buy OKTW, but can not receive verification mail

### ISSUE THREAD

**Issue by tlerbao** [OneKeyToWin/OKTW.ME#9]
I registered the account, ready to buy OKTW, but can not receive verification mail

**Comment by tlerbao** [comment]
Registered twice. Both mailboxes can not receive a verification email.
398983521@qq.com & tl_weige@163.com

**Comment by tlerbao** [comment]
gmail also can not receive verification mail
tlweige@gmail.com

**Comment by Daeral** [comment]
E-mail issues are now fixed and the service is fully operational and online. We are now monitoring it, to not let this happen again. Sorry for inconveniences.
